name = "podcast-stats"
main = "src/cron.ts"
compatibility_date = "2023-12-18"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *", "*/3 * * * *"]

[dev]
port = 8080

[[d1_databases]]
binding = "D1"
database_name = "podcast-stats-prod"
database_id = "e2659b9a-928c-4218-beb5-518b87f59c4f"
